# @format

name: lens-analysis
channels:
  - defaults
dependencies:
  - python=3.8.11
  - patsy
  - scikit-learn
  - numpy
  - pandas
# prefix: /opt/homebrew/Caskroom/miniconda/base/envs/lens-analysis
